### ISSUE TITLE
win 下安装到swoole报错报错

### ISSUE THREAD

**Issue by September999999999** [jianyan74/dockerfiles#1]
`Package "swoole" Version "4.4.5" does not have REST xml available
download failed
ERROR: Service 'php-fpm' failed to build: The command '/bin/sh -c cd /usr/src     && pecl download swoole-${SWOOLE_VER}     && tar -zxvf swoole-${SWOOLE_VER}.tgz     && cd swoole-${SWOOLE_VER}     && phpize     && ./configure --with-php-config=/usr/local/bin/php-config --enable-openssl     && make     && make install     && echo "extension=swoole.so" > /usr/local/etc/php/conf.d/swoole.ini     && rm -rf swoole-${SWOOLE_VER}.tgz     && rm -rf swoole-${SWOOLE_VER}' returned a non-zero code: 1`

**Comment by jianyan74** [comment]
用linux哈
